### PR TITLE
Create post page

### PR DESCRIPTION
**Pull request by wrt95**
Branch name is wrong, but this PR has fixed the Android error. The fix was done by using the Footer component from the style guide, and assigning it the type "fontAwsome5".  

How it looks in iOS (left) and Android (right)
Screenshot 2021-01-11 at 16 33 05

### CODE REVIEW

**Review by calumshep — COMMENTED** [review]
All looks good but not sure about committing the `assets/` dir if this is something that's compiled by npm?

**Comment by wrt95** [comment]
@calumshep 
The files are deleted, so doing that commit will remove them from the repo as they are not needed.

**Review by rb114-hw — APPROVED** [review]
Nice work!

**Comment by calumshep** [comment]
> @calumshep
> The files are deleted, so doing that commit will remove them from the repo as they are not needed.

Just getting my inability to read out of my system straight off the bat lol...

**Review by calumshep — APPROVED** [review]

**Pull request merged**
