### PR TITLE
Moderation

### PR DESCRIPTION
**Pull request by sp103**
### ChannelOptions.tsx
Gives moderators options for each channel they moderate
Screenshot_1615387264

### ManageChannel.tsx
used in ChannelOption.,tsx to give options
Screenshot_1615387264

### ManagePosts.tsx
Page to display options for each post in a channel
Screenshot_1615387354

### PostOptions.tsx
Component to display options on ManagePosts.tsx
Screenshot_1615387354

### ManageUsers.tsx
Page to give options for each user in a channel
Screenshot_1615387429

### UserOptions.tsx
Component to display options on ManageUsers.tsx
Screenshot_1615387429

### EditChannel.tsx
Edited to new format, removing image selection and adding challenges and rules
Screenshot_1615387475
Screenshot_1615387478

### Rule.tsx
Displays rule on editChannel.tsx
Screenshot_1615387475

### Challenge.tsx
Displays challenge on editChannel.tsx
Screenshot_1615387478

### Types.ts
Added types for challenge and rule

### AddChallenge.tsx
Popup page to allow moderators to add a new challenge
Used in editChannel.tsx
Screenshot_1615387583

### DummyChannelValues.ts
Placeholder values for use unitl backend connection

### GetChannelValues.tsx
Contains functions to return challenges and rules for display in EditChannel.tsx

### NewsFeed.tsx
Added button that brings up PasswordPopup.tsx
Screenshot_1615387600

### NewsfeedNavigator.tsx
Added moderation pages

### PasswordPopup.tsx
Asks the user to re-enter their password and leads to ManageChannels.tsx
Screenshot_1615387626

### DatePicker.tsx
Added different style and option for date return instead of string

### TextAreaForm
Added style option for 100% width
Added option for numpad keyboard

### CODE REVIEW

**Review by wrt95 — APPROVED** [review]
Looks very good!

**Review by calumshep — CHANGES_REQUESTED** [review]
Possible for these buttons on the right to all be the same size?

image

Also can the `PostOptions` be in the new design we talked about with stacked (or closer) moderation buttons on the right and a preview/thumbnail of the post image on the right?

**Comment by wrt95** [comment]
@calumshep 
This you mean?
Screenshot 2021-03-11 at 10 30 01

**Comment by calumshep** [comment]
> @calumshep
> This you mean?
> Screenshot 2021-03-11 at 10 30 01

Yeah, with the search box being a long-term feature

**Comment by wrt95** [comment]
Perfect! 
@sp103 can you quickly redesign it? Dont do the search bar yet

**Comment by calumshep** [comment]
Just as an afterthought, could include the post title above the view/delete links? Might just help moderators find the right post along with the thumbnail.

**Comment by sp103** [comment]
@calumshep 
do you mean like this?
Screenshot_1615456533
Screenshot_1615456544

**Review by calumshep — APPROVED** [review]
Yeah, looks great! Thanks

**Comment by wrt95** [comment]
Perfect! 
Good job @sp103!

**Pull request merged**
